# Generated by Django 5.0.3 on 2024-03-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_quantity_size_remove_product_size_productquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantities',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
