# Generated by Django 5.0.3 on 2024-04-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_available_sizes_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='it_is_very_sold',
            field=models.BooleanField(default=False),
        ),
    ]
