# Generated by Django 5.0.3 on 2024-03-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_size'),
        ('store', '0006_remove_product_available_sizes_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
